service: custom-authorizer

provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-1
  environment:
    POWERTOOLS_LOG_LEVEL: DEBUG

plugins:
  - serverless-provisioned-concurrency-autoscaling
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false        # use docker to build deps for correct OS/arch
    layer: true              # or true if you want dependencies in a Lambda layer
    slim: true                # reduce package size
    strip: false

functions:
  authorizer:
    handler: authorizer.handler.authorize
    layers:
        - Ref: PythonRequirementsLambdaLayer
    # provisionedConcurrency: 1
    # concurrencyAutoscaling:
    #   enabled: true
    #   alias: provisioned
    #   maximum: 10
    #   minimum: 1
    #   usage: 0.75
    #   scaleInCooldown: 0
    #   scaleOutCooldown: 0