service: lambda-api-config

provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-1
  environment:
    S3_BUCKET: benjo-s3bucket-001
    S3_KEY: api_config.json
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:ListBucket
      Resource: arn:aws:s3:::benjo-s3bucket-001/api_config.json

functions:
  getApiConfig:
    handler: handler.get_api_config
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline