service: custom-authorizer

provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-1

plugins:
  - serverless-provisioned-concurrency-autoscaling

functions:
  authorizer:
    handler: handler.authorize
    provisionedConcurrency: 1
    concurrencyAutoscaling:
      enabled: true
      alias: provisioned
      minimum: 1
      maximum: 2
      usage: 0.75
      scaleInCooldown: 30
      scaleOutCooldown: 30